name: Yang iproute2 CI
run-name: ${{ github.actor }} basic compilation and test ⚗️
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build-iproute2-sysrepo:
    name: Build iproute2-sysrepo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
    steps:
      - name: add missing packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: libelf-dev libbpf-dev libbsd-dev libcap-dev libmnl-dev libselinux-dev libyang-tools
      - name: recursive checkout (with iproute2 submodule)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: sysrepo v2.2.150 from upstream
        uses: actions/checkout@v4
        with:
          repository: 'sysrepo/sysrepo.git'
          ref: 'v2.2.150'
      - name: make sysrepo v2.2.150 from upstream
        run: mkdir build && cd build && cmake -DLIBYANG_LIBRARY:PATH=$(pwd)/bin -DLIBYANG_INCLUDE_DIR:PATH=$(pwd)/bin -DCMAKE_LIBRARY_PATH:PATH=$(pwd)/bin -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/bin -DCMAKE_BUILD_TYPE:String="Release" .. && make -j $(nproc) && make install
      - name: check sysrepo running ok
        run: sysrepoctl -l
      - name: make iproute2-sysrepo
        run: CC=${{ matrix.compiler }} make -j $(nproc)
      - name: basic compilation check
        run: ldd bin/iproute2-sysrepo
      - name: basic test ip address like
        run: bin/iproute2-sysrepo link
      - name: yanglint
        run: make check
