name: Yang iproute2 CI
run-name: ${{ github.actor }} basic compilation ⚗️
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build-yp-sr:
    name: Build yp_sr
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
    steps:
      - name: add missing packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: libelf-dev libbpf-dev libbsd-dev libsysrepo-dev libcap-dev libmnl-dev libselinux-dev
      - name: recursive checkout (with iproute2 submodule)
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: make yp_sr
        run : CC=${{ matrix.compiler }} make -j $(nproc)
      - name: basic run
        run : ldd bin/yp_sr
